// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config/config.dart'; // Import the config file for API keys

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// \`\`\`dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// \`\`\`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Load values from environment variables via config.dart
  static final FirebaseOptions web = FirebaseOptions(
    apiKey: AppConfig.apiKey,
    appId: AppConfig.appId,
    messagingSenderId: AppConfig.messagingSenderId,
    projectId: AppConfig.projectId,
    authDomain: '${AppConfig.projectId}.firebaseapp.com',
    storageBucket: AppConfig.storageBucket,
    measurementId: 'G-5BM9E22QY8',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: AppConfig.apiKey,
    appId: AppConfig.appId,
    messagingSenderId: AppConfig.messagingSenderId,
    projectId: AppConfig.projectId,
    storageBucket: AppConfig.storageBucket,
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: AppConfig.apiKey,
    appId: AppConfig.appId,
    messagingSenderId: AppConfig.messagingSenderId,
    projectId: AppConfig.projectId,
    storageBucket: AppConfig.storageBucket,
    iosBundleId: 'com.example.flutterApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: AppConfig.apiKey,
    appId: AppConfig.appId,
    messagingSenderId: AppConfig.messagingSenderId,
    projectId: AppConfig.projectId,
    storageBucket: AppConfig.storageBucket,
    iosBundleId: 'com.example.flutterApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: AppConfig.apiKey,
    appId: AppConfig.appId,
    messagingSenderId: AppConfig.messagingSenderId,
    projectId: AppConfig.projectId,
    authDomain: '${AppConfig.projectId}.firebaseapp.com',
    storageBucket: AppConfig.storageBucket,
    measurementId: 'G-SKL6V2N9NF',
  );
}
